#!/usr/bin/env python3
"""anchors-table.py — independent oracle for dsh-webfetch table extraction.

R41: expected values for test/table.test.ts generated by this script, NOT
hand-written. The oracle implements the documented semantics with a different
parser (stdlib html.parser, CDATA-aware) than the TypeScript walker, so
agreement between the two is meaningful.

Documented semantics mirrored here:
- outermost tables only; nested table text flattens into the containing cell
  (a space is inserted at nested cell boundaries)
- colspan/rowspan expand to a rectangular grid; spanning text repeats in
  every covered slot
- header = first row when it is inside <thead> or all cells are <th>
- entity-decoded, whitespace-normalized cell text, 200-char cap + '…'
- tables without any cell are ignored

Run:  python3 test/anchors-table.py          (prints JSON fixture -> expected)
"""

import json
import re
import sys
from html.parser import HTMLParser

MAX_CELL = 200
RAW_SKIP = {"script", "style", "noscript", "template"}
TEXT_SKIP = {"svg", "math", "select", "textarea", "iframe", "object",
             "canvas", "audio", "video", "head", "title"}

WS_RE = re.compile(r"\s+")


def norm(text: str) -> str:
    return WS_RE.sub(" ", text).strip()


def span(value):
    if value is None:
        return 1
    try:
        n = int(str(value).strip())
    except ValueError:
        return 1
    return min(n, 100) if n >= 2 else 1


def setc(out, idx, val):
    while len(out) <= idx:
        out.append("")
    out[idx] = val


class Oracle(HTMLParser):
    def __init__(self):
        super().__init__(convert_charrefs=True)
        self.depth = 0
        self.tables = []          # emitted tables (in page order)
        self.skip_stack = []      # active TEXT_SKIP / RAW_SKIP tag names
        self._reset_table()

    def _reset_table(self):
        self.rows = None
        self.row_cells = None
        self.row_thead = False
        self.in_thead = False
        self.cell = None
        self.caption = None
        self.in_caption = False

    # --- cell / row / table flushing -------------------------------------
    def flush_cell(self):
        if self.cell is None:
            return
        text = norm(self.cell["text"])
        if len(text) > MAX_CELL:
            text = text[:MAX_CELL] + "\u2026"
        if self.row_cells is None:
            self.row_cells = []
        self.row_cells.append({**self.cell, "text": text})
        self.cell = None

    def flush_row(self):
        self.flush_cell()
        if self.row_cells and self.rows is not None:
            self.rows.append({"cells": self.row_cells, "thead": self.row_thead})
        self.row_cells = None

    def close_table(self):
        self.flush_row()
        if self.rows and any(row["cells"] for row in self.rows):
            self.tables.append({
                "caption": norm(self.caption) if self.caption else "",
                "rows": self.rows,
            })
        self._reset_table()

    # --- parser callbacks -------------------------------------------------
    def handle_starttag(self, tag, attrs):
        tag = tag.lower()
        if tag in RAW_SKIP:
            self.skip_stack.append(tag)
            return
        if self.skip_stack:
            if tag in TEXT_SKIP:
                self.skip_stack.append(tag)
            return
        if tag == "br":
            if self.in_caption and self.caption is not None:
                self.caption += " "
            elif self.cell is not None:
                self.cell["text"] += " "
            return

        if tag == "table":
            self.depth += 1
            if self.depth == 1:
                self._reset_table()
                self.rows = []
            return
        if self.depth != 1:
            # Inside a nested table: cell boundaries become separators.
            if tag in ("td", "th") and self.cell is not None:
                self.cell["text"] += " "
            return
        amap = {k.lower(): (v or "") for k, v in attrs}
        if tag == "caption":
            if self.caption is None:
                self.in_caption = True
                self.caption = ""
        elif tag == "thead":
            self.in_thead = True
        elif tag in ("tbody", "tfoot"):
            self.in_thead = False
        elif tag == "tr":
            self.flush_row()
            self.row_thead = self.in_thead
        elif tag in ("td", "th"):
            self.flush_cell()
            if self.row_cells is None:
                self.row_cells = []
            self.cell = {"text": "", "colspan": span(amap.get("colspan")),
                         "rowspan": span(amap.get("rowspan")),
                         "is_header": tag == "th"}

    def handle_endtag(self, tag):
        tag = tag.lower()
        if self.skip_stack:
            if tag == self.skip_stack[-1]:
                self.skip_stack.pop()
            return
        if tag == "table":
            if self.depth >= 1:
                if self.depth == 1:
                    self.close_table()
                self.depth -= 1
            return
        if self.depth != 1:
            return
        if tag == "tr":
            self.flush_row()
        elif tag in ("td", "th"):
            self.flush_cell()
        elif tag == "thead":
            self.flush_row()
            self.in_thead = False
        elif tag in ("tbody", "tfoot"):
            self.flush_row()
        elif tag == "caption":
            self.in_caption = False

    def handle_data(self, data):
        if self.skip_stack:
            return
        if self.in_caption and self.caption is not None:
            self.caption += data
        elif self.cell is not None:
            self.cell["text"] += data

    def close(self):
        super().close()
        if self.rows is not None:
            self.close_table()
            self.depth = 0


def build_grid(rows):
    grid = []
    pending = {}
    for row in rows:
        out = []
        col = 0

        def place(col):
            while col in pending and pending[col]["remaining"] > 0:
                setc(out, col, pending[col]["text"])
                pending[col]["remaining"] -= 1
                if pending[col]["remaining"] == 0:
                    del pending[col]
                col += 1
            return col

        for cell in row["cells"]:
            col = place(col)
            for k in range(cell["colspan"]):
                setc(out, col + k, cell["text"])
            if cell["rowspan"] > 1:
                for k in range(cell["colspan"]):
                    pending[col + k] = {"text": cell["text"], "remaining": cell["rowspan"] - 1}
            col += cell["colspan"]
        col = place(col)
        grid.append(out)
    return grid


def extract(html, max_tables=10, max_rows=100):
    parser = Oracle()
    parser.feed(html)
    parser.close()
    tables = []
    row_capped = False
    for t in parser.tables[:max_tables]:
        grid = build_grid(t["rows"])
        cols = max((len(r) for r in grid), default=0)
        for r in grid:
            while len(r) < cols:
                r.append("")
        first = t["rows"][0]
        header_row = first["thead"] or all(c["is_header"] for c in first["cells"])
        header = grid[0] if header_row else []
        body = grid[1:] if header_row else grid
        if len(body) > max_rows:
            body = body[:max_rows]
            row_capped = True
        tables.append({"index": len(tables) + 1, "caption": t["caption"],
                       "cols": cols, "header": header, "rows": body})
    truncated = len(parser.tables) > max_tables or row_capped
    return {"tables": tables, "totalTables": len(parser.tables), "truncated": truncated}


FIXTURES = {
    "F1_simple_thead": '<table><thead><tr><th>Name</th><th>Score</th></tr></thead>'
                       '<tbody><tr><td>Ann</td><td>90</td></tr><tr><td>Bob</td><td>85</td></tr></tbody></table>',
    "F2_th_first_row": '<table><tr><th>A</th><th>B</th></tr><tr><td>1</td><td>2</td></tr></table>',
    "F3_no_header": '<table><tr><td>x</td><td>y</td></tr></table>',
    "F4_colspan_header": '<table><tr><th>A</th><th colspan="2">Group B</th></tr>'
                         '<tr><td>1</td><td>2</td><td>3</td></tr></table>',
    "F5_rowspan": '<table><tr><td rowspan="2">x</td><td>1</td></tr><tr><td>2</td></tr></table>',
    "F6_span_grid": '<table><tr><th rowspan="2">H</th><th colspan="2">Top</th></tr>'
                    '<tr><td>a</td><td>b</td></tr><tr><td>c</td><td>d</td><td>e</td></tr></table>',
    "F7_nested": '<table><tr><td>outer <table><tr><td>in1</td><td>in2</td></tr></table> end</td>'
                 '<td>right</td></tr></table>',
    "F8_caption_entities": '<table><caption>Sales &amp; Costs 2024</caption>'
                           '<tr><th>Item</th></tr><tr><td>A&nbsp;B &#169;</td></tr></table>',
    "F9_br_whitespace": '<table><tr><td>line1<br>line2</td><td>  padded   text </td></tr></table>',
    "F13_skip_tags": '<table><tr><td>ok<script>evil()</script><style>.x{}</style></td></tr></table>',
    "F14_malformed": '<table><tr><td>a<td>b</table>',
    "F15_empty_skipped": '<table></table><table><tr><td>real</td></tr></table>',
    "F16_thead_td": '<table><thead><tr><td>P</td><td>Q</td></tr></thead>'
                    '<tbody><tr><td>1</td><td>2</td></tr></tbody></table>',
    "F17_mixed_first_row": '<table><tr><th>A</th><td>b</td></tr><tr><td>1</td><td>2</td></tr></table>',
    "F19_uppercase": '<TABLE><TR><TD>Up</TD></TR></TABLE>',
    "F21_script_table_text": '<table><tr><td>ok</td></tr></table>'
                             '<script>var s = "</table><table><tr><td>fake</td></tr>";</script>'
                             '<table><tr><td>second</td></tr></table>',
    "F22_rag": '<table><tr><td>a</td><td>b</td></tr><tr><td>c</td></tr></table>',
    "F23_unclosed_eof": '<table><tr><td>only</td></tr>',
    "F24_span_caps": '<table><tr><td colspan="9999">wide</td></tr></table>',
    "F25_invalid_spans": '<table><tr><td colspan="0">a</td><td colspan="x">b</td><td rowspan="-3">c</td></tr></table>',
}

if __name__ == "__main__":
    out = {}
    for name, html in FIXTURES.items():
        out[name] = extract(html)
    many_rows = "<table>" + "".join(f"<tr><td>r{i}</td></tr>" for i in range(1, 61)) + "</table>"
    many_tables = "".join(f"<table><tr><td>t{i}</td></tr></table>" for i in range(1, 8))
    truncated_cell = "<table><tr><td>" + "a" * 250 + "</td></tr></table>"
    out["C1_max_rows"] = extract(many_rows, max_rows=50)
    out["C2_max_tables"] = extract(many_tables, max_tables=5)
    out["C3_cell_trunc"] = extract(truncated_cell)
    json.dump(out, sys.stdout, ensure_ascii=False, indent=1)
    print()
